### PR TITLE
Prevent default `convert` method override for topologies

### LINKED ISSUE #177: SimpleMesh fails with generic Vector{Connectivity}
With
`vertices = Point3[(0, 0 , 0), (1, 0, 0), (1, 1, 1), (0, 1, 0)]`
`elements = connect.([(1,2,3,4),(3,4,1)], [Tetrahedron, Triangle])`
`SimpleMesh(vertices, elements)`

I got output

> ERROR: TypeError: in new, expected FullTopology{Connectivity}, got a value 
of type FullTopology{Connectivity{Tetrahedron, 4}}
Stacktrace:
 [1] SimpleMesh (repeats 2 times)
   @ C:\Users\delta\.julia\packages\Meshes\LXhFZ\src\mesh\simplemesh.jl:20 
[inlined]
 [2] SimpleMesh(points::Vector{Point3}, connec::Vector{Connectivity})      
   @ Meshes C:\Users\delta\.julia\packages\Meshes\LXhFZ\src\mesh\simplemesh.jl:25
 [3] top-level scope
   @ REPL[51]:1

using Hexahedron lead to the same result

Julia version info

> Julia Version 1.7.0-rc1
Commit 9eade6195e (2021-09-12 06:45 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
  JULIA_PKG_SERVER = https://mirrors.tuna.tsinghua.edu.cn/julia

### PR DESCRIPTION
**Pull request by serenity4**
Fixes #177.

### CODE REVIEW

**Comment by juliohm** [comment]
I think the PR is using an outdated branch?

**Comment by serenity4** [comment]
Yes, you beat me to it. It is now up to date.

**Comment by juliohm** [comment]
Codecov is so weird sometimes. It is saying that coverage decreased? 🤔

File: test/mesh.jl [hunk 1]
```diff
@@ -179,6 +179,11 @@
     end
     @test eltype(mesh) <: Polygon{2,T}
 
+    points = P3[(0,0,0),(1,0,0),(1,1,1),(0,1,0)]
+    elms = connect.([(1,2,3,4),(3,4,1)], [Tetrahedron, Triangle])
+    mesh = SimpleMesh(points, elms)
+    @test [2, 3] ⊆ topology(mesh).ranks
```
Comment (juliohm) [inline test/mesh.jl]: Maybe `paramdim.(mesh) == [3,2]`?

Comment (juliohm) [inline test/mesh.jl]:
```suggestion
    @test paramdim.(mesh) == [3,2]
```

File: test/mesh.jl [hunk 2]
```diff
@@ -179,6 +179,11 @@
     end
     @test eltype(mesh) <: Polygon{2,T}
 
+    points = P3[(0,0,0),(1,0,0),(1,1,1),(0,1,0)]
```
Comment (juliohm) [inline test/mesh.jl:183]:
```suggestion
    # test for https://github.com/JuliaGeometry/Meshes.jl/issues/177
    points = P3[(0,0,0),(1,0,0),(1,1,1),(0,1,0)]
```

**Comment by juliohm** [comment]
Interestingly the test is failing after my suggested change. 🤔

File: test/mesh.jl [hunk 3]
```diff
@@ -179,6 +179,12 @@
     end
     @test eltype(mesh) <: Polygon{2,T}
 
+    # test for https://github.com/JuliaGeometry/Meshes.jl/issues/177
+    points = P3[(0,0,0),(1,0,0),(1,1,1),(0,1,0)]
+    elms = connect.([(1,2,3,4),(3,4,1)], [Tetrahedron, Triangle])
+    mesh = SimpleMesh(points, elms)
+    @test paramdim.(mesh) == [3,2]
```
Comment (serenity4) [inline test/mesh.jl]: Do you really intend to broadcast over `mesh`? Do we have a custom broadcasting on `SimpleMesh`?

Comment (juliohm) [reply test/mesh.jl]: Oh my mistake, the broadcast will be over the elements of the mesh only, discarding the geometries of lower rank. I think what we want is `faces(mesh, 2) == [Triangle(P3[(), (), ()])]` and `faces(mesh, 3) == [Tetrahedron(P3[(), (), (), ()])`

Comment (juliohm) [reply test/mesh.jl]: We can get the faces of the mesh or the faces of the topology of the mesh.

Comment (serenity4) [reply test/mesh.jl]: As you prefer, I originally checked the rank of the topology because that's what was prone to issues (notably with the modified `convert` that was taken which reconstructs only elements of higher rank). What we want above all is just for the code not to error. If you think a more elaborate check is more appropriate feel free to add one.

Comment (juliohm) [inline test/mesh.jl]:
```suggestion
    connec = connect.([(1,2,3,4),(3,4,1)], [Tetrahedron, Triangle])
    mesh = SimpleMesh(points, connec)
    topo = topology(mesh)
    @test collect(faces(topo, 2)) == [connect((3,4,1), Triangle)
    @test collect(faces(topo, 3)) == [connect((1,2,3,4), Tetrahedron)
```

File: test/mesh.jl [hunk 4]
```diff
@@ -179,6 +179,14 @@
     end
     @test eltype(mesh) <: Polygon{2,T}
 
+    # test for https://github.com/JuliaGeometry/Meshes.jl/issues/177
+    points = P3[(0,0,0),(1,0,0),(1,1,1),(0,1,0)]
+    connec = connect.([(1,2,3,4),(3,4,1)], [Tetrahedron, Triangle])
+    mesh = SimpleMesh(points, connec)
+    topo = topology(mesh)
+    @test collect(faces(topo, 2)) == [connect((3,4,1), Triangle)
+    @test collect(faces(topo, 3)) == [connect((1,2,3,4), Tetrahedron)
```
Comment (juliohm) [inline test/mesh.jl]:
```suggestion
    @test collect(faces(topo, 2)) == [connect((3,4,1), Triangle)]
    @test collect(faces(topo, 3)) == [connect((1,2,3,4), Tetrahedron)]
```

**Comment by juliohm** [comment]
Thanks for the help as usual! =)
