### PR TITLE
force Float64 Point

### LINKED ISSUE #161: Constructors with Integer literals should convert to floating point coordinates
If I try to sample from a triangle whose vertices are float points, nothing is wrong. 
```julia 
julia> Ω = Ngon(Point(0., 1.), Point(1., 0.), Point(1., 1.))
Triangle{2,Float64}
  └─Point(0.0, 1.0)
  └─Point(1.0, 0.0)
  └─Point(1.0, 1.0)

julia> pnt = sample(Ω, HomogeneousSampling(5)) |> collect
5-element Vector{Point2}:
 Point(0.445212832411942, 0.9489938469778333)
 Point(0.43267110681743415, 0.8483702741628089)
 Point(0.9689446652731993, 0.49281098786470057)
 Point(0.940827342417384, 0.2071168869475296)
 Point(0.5334816086641955, 0.9112811451205238)
```
However if types of the vertices are integer, then I get a DomainError. 
```julia 
ulia> Ω = Ngon(Point(0, 1), Point(1, 0), Point(1, 1))
Triangle{2,Int64}
  └─Point(0, 1)
  └─Point(1, 0)
  └─Point(1, 1)

julia> pnt = sample(Ω, HomogeneousSampling(5)) |> collect
ERROR: DomainError with -3.3173935348431923e18:
sqrt will only return a complex result if called with a complex argument. Try sqrt(Complex(x)).
Stacktrace:
  [1] throw_complex_domainerror(f::Symbol, x::Float64)
    @ Base.Math ./math.jl:33
  [2] sqrt
    @ ./math.jl:582 [inlined]
  [3] sqrt
    @ ./math.jl:608 [inlined]
  [4] (::Meshes.var"#randpoint#172"{Int64, StaticArrays.SVector{2, Int64}, StaticArrays.SVector{2, Int64}, StaticArrays.SVector{2, Int64}})()
    @ Meshes ~/.julia/packages/Meshes/0vOB2/src/sampling/homogeneous.jl:38
  [5] #171
    @ ./generator.jl:0 [inlined]
  [6] iterate
    @ ./generator.jl:47 [inlined]
  [7] iterate
    @ ~/.julia/packages/IterTools/0dYLc/src/IterTools.jl:869 [inlined]
  [8] collect_to!
    @ ./array.jl:724 [inlined]
  [9] collect_to_with_first!(dest::Vector{Point2}, v1::Point2, itr::IterTools.IVec{Base.Generator{UnitRange{Int64}, Meshes.var"#171#173"{Meshes.var"#randpoint#172"{Int64, StaticArrays.SVector{2, Int64}, StaticArrays.SVector{2, Int64}, StaticArrays.SVector{2, Int64}}}}}, st::Int64)
    @ Base ./array.jl:702
 [10] _collect(c::UnitRange{Int64}, itr::IterTools.IVec{Base.Generator{UnitRange{Int64}, Meshes.var"#171#173"{Meshes.var"#randpoint#172"{Int64, StaticArrays.SVector{2, Int64}, StaticArrays.SVector{2, Int64}, StaticArrays.SVector{2, Int64}}}}}, #unused#::Base.EltypeUnknown, isz::Base.HasLength)
    @ Base ./array.jl:696
 [11] collect
    @ ./array.jl:602 [inlined]
 [12] |>(x::IterTools.IVec{Base.Generator{UnitRange{Int64}, Meshes.var"#171#173"{Meshes.var"#randpoint#172"{Int64, StaticArrays.SVector{2, Int64}, StaticArrays.SVector{2, Int64}, StaticArrays.SVector{2, Int64}}}}}, f::typeof(collect))
    @ Base ./operators.jl:858
 [13] top-level scope
    @ REPL[59]:1
julia> 
```
I think this looks awkward and worths opening an issue here,

### PR DESCRIPTION
**Pull request by HaoxuanGuo**
Fix #161 .

### CODE REVIEW

File: src/points.jl [hunk 1]
```diff
@@ -29,6 +29,7 @@ Point{Dim,T}(coords...) where {Dim,T} = Point{Dim,T}(SVector{Dim,T}(coords...))
 Point(coords::SVector{Dim,T}) where {Dim,T} = Point{Dim,T}(coords)
 Point(coords::AbstractVector{T}) where {T} = Point{length(coords),T}(coords)
 Point(coords...) = Point(SVector(coords...))
+Point(coords::SVector{Dim,T}) where {Dim,T<:Integer} = Point(SVector{Dim, Float64}(coords))
```
Comment (juliohm) [inline src/points.jl]: Maybe this conversion should happen inside our inner constructor whenever `T <: Integer`?

**Comment by GuoHaoxuan** [comment]
@juliohm You are right. What about now?

File: src/points.jl [hunk 2]
```diff
@@ -22,6 +22,7 @@ O = Point(0.0, 0.0) # origin of 2D Euclidean space
 struct Point{Dim,T}
   coords::SVector{Dim,T}
   Point{Dim,T}(coords::SVector) where {Dim,T} = new{Dim,T}(coords)
+  Point{Dim,T}(coords::SVector{Dim,T2}) where {Dim,T,T2<:Integer} = new{Dim,Float64}(coords)
```
Comment (juliohm) [inline src/points.jl]: Maybe we need to convert the type differently?

```julia
struct Point{Dim,T}
  coords::SVector{Dim,T}
  function Point{Dim,T}(coords) where {Dim,T}
    eltype(coords) <: Integer ? new(Float64.(coords)) : new(coords)
  end
end
```

Does that work? I am not very familiar with the machinery behind inner constructors. We also need to double check that this is efficient.

Comment (hx-guo) [reply src/points.jl]: Maybe we should use the multiple-dispatch to dispatch `SVector{Dim,T} where T<:Integer` separately instead of make it manual. I am not familiar that, too.

Comment (serenity4) [reply src/points.jl]: I am not sure we need inner constructors at all. Maybe we can keep the default constructors, and add a method `Point(coords::SVector{Dim,<:Integer}) where {Dim} = Point(convert(SVector{Dim,Float64}, coords))`

Comment (juliohm) [reply src/points.jl]: Yes, I find inner constructors a bit difficult to grasp, but remember someone added it to handle the ambiguities with the outer constructors somehow. If we can eliminate the inner constructor and still convert Integer coordinates do Float64 that would be a double win. Appreciate any help on this.

I think our test suite is already covering the past issues people had with Point constructors.

Comment (juliohm) [reply src/points.jl]: @HaoxuanGuo did your previous attempt with an external constructor worked fine? All tests passed?

Comment (hx-guo) [reply src/points.jl]: @juliohm Both the 2 inner or outer one works well. You may notice that there are some test cases not passed. Because they are

```julia
@test coordtype(Point(1, 1)) == Int
@test coordtype(Point([1])) == Int
@test coordtype(Point([1,2])) == Int
@test coordtype(Point([1,2,3])) == Int
```

Obviously, we want to convert them to `Float64` instead of `Int`. It not passed is just our expected.

So, both them are worked fine, but not all tests passed. While **`not all tests passed` is our expected**.

Comment (juliohm) [reply src/points.jl]: Nice, feel free to update the tests to match the new behavior. I can review the PR again by the end of the day. Thanks for this must needed addition.

**Comment by GuoHaoxuan** [comment]
@juliohm I changed the tests to adapt the behavior. Left the construction as inner one.

File: src/points.jl (hunk 2 above)
Comment (juliohm) [inline src/points.jl]:
```suggestion
  Point{Dim,T}(coords::SVector{Dim,V}) where {Dim,T,V<:Integer} = new{Dim,Float64}(coords)
```

**Review by juliohm — APPROVED** [review]

**Comment by juliohm** [comment]
That is awesome @HaoxuanGuo 🚀 Approved the PR.

@serenity4 are we good to go? Any other comment before we merge this? It is a simple but sensitive change of behavior.

**Review by serenity4 — APPROVED** [review]
Looks good to me.

**Comment by juliohm** [comment]
Amazing @HaoxuanGuo ! 👌🏽
