### PR TITLE
Fix units bug in `Disk` parametrization function

### LINKED ISSUE #1254: A Circle defined with mixed units can parametrize incorrectly
# MWE

This `circle` function produces a `Circle` on the xy-plane, centered on the origin, and with a specified radius. Internally, the other `Point` and `Vec`s used to construct the `Circle` are unitless, which Meshes promotes as implicitly representing distances in meters.
```julia
using Meshes
using Unitful

function circle(radius)
	origin = Meshes.Point(0, 0, 0)
	x = Meshes.Vec(1, 0, 0)
	y = Meshes.Vec(0, 1, 0)
	plane = Meshes.Plane(origin, x, y)
	Meshes.Circle(plane, radius)
end

ts = range(0, 1, length=5)
```

If the circle is defined with a 1 mm radius in a meters Quantity type, then the result is as expected.
```julia
julia> circle(0.001u"m").(ts)
5-element Vector{Point{𝔼{3}, CoordRefSystems.Cartesian3D{CoordRefSystems.NoDatum, Quantity{Float64, 𝐋, Unitful.FreeUnits{(m,), 𝐋, nothing}}}}}:
 Point(x: 0.001 m, y: 0.0 m, z: 0.0 m)
 Point(x: 0.0 m, y: 0.001 m, z: 0.0 m)
 Point(x: -0.001 m, y: 0.0 m, z: 0.0 m)
 Point(x: 0.0 m, y: -0.001 m, z: 0.0 m)
 Point(x: 0.001 m, y: 0.0 m, z: 0.0 m)
```

If the circle is defined with a 1 mm radius in a millimeters Quantity type, then the resulting coordinates correspond instead to a circle with a 1 meter radius.
```julia
julia> circle(1.0u"mm").(ts)
5-element Vector{Point{𝔼{3}, CoordRefSystems.Cartesian3D{CoordRefSystems.NoDatum, Quantity{Float64, 𝐋, Unitful.FreeUnits{(m,), 𝐋, nothing}}}}}:
 Point(x: 1.0 m, y: 0.0 m, z: 0.0 m)
 Point(x: 0.0 m, y: 1.0 m, z: 0.0 m)
 Point(x: -1.0 m, y: 0.0 m, z: 0.0 m)
 Point(x: 0.0 m, y: -1.0 m, z: 0.0 m)
 Point(x: 1.0 m, y: 0.0 m, z: 0.0 m)
```

# Debugging

I haven't had time yet to debug this but I suspect it's caused by the single-argument `ustrip`s here:
https://github.com/JuliaGeometry/Meshes.jl/blob/eeedffaa2a380e3899713ff03e5c46eb2a18ba23/src/geometries/primitives/disk.jl#L36-L46

### PR DESCRIPTION
**Pull request by mikeingold**
# Changes

- Fixes bug in parametrization function for `Disk` that produced incorrect results when `Disk` (or `Circle`) were constructed with mixed units.
- Adds tests for mixed-unit construction results to `Ball`, `Circle`, `Disk`, and `Sphere` test sets.

Closes #1254

### CODE REVIEW

File: src/geometries/primitives/disk.jl [hunk 1]
```diff
@@ -37,10 +37,12 @@ function (d::Disk)(ρ, φ)
...
-  T = numtype(lentype(d))
+  L = lentype(d)
+  units = unit(L)
+  T = numtype(L)
   l = T(ρ) * radius(d)
   sφ, cφ = sincospi(2 * T(φ))
-  u = ustrip(l * cφ)
-  v = ustrip(l * sφ)
+  u = ustrip(units, l * cφ)
+  v = ustrip(units, l * sφ)
```
Comment (juliohm) [inline src/geometries/primitives/disk.jl]:
```suggestion
  ℒ = lentype(d)
  T = numtype(ℒ)
  l = T(ρ) * radius(d)
  sφ, cφ = sincospi(2 * T(φ))
  u = ustrip(unit(ℒ), l * cφ)
  v = ustrip(unit(ℒ), l * sφ)
```

File: test/primitives.jl [hunk 2]
```diff
@@ -698,6 +698,11 @@ end
   @test cart(0, 0, 2) ∈ s
   @test cart(3, 5, 2) ∉ s
 
+  # Ensure mixed-unit construction produces correct parametrization
+  r = T(1) * u"mm"
+  s = Sphere(cart(0, 0, 0), r)
+  @test LinearAlgebra.norm(s(1, 0) - center(s)) == r
```
Comment (juliohm) [inline test/primitives.jl]:
```suggestion
  @test norm(s(1, 0) - center(s)) == r
```

File: test/primitives.jl [hunk 3]
```diff
@@ -798,6 +803,12 @@ end
   @test cart(0, 0, 1) ∉ d
   @test boundary(d) == Circle(p, T(2))
 
+  # Ensure mixed-unit construction produces correct parametrization
+  p = Plane(cart(0, 0, 0), vector(0, 0, 1))
+  r = T(1) * u"mm"
+  d = Disk(p, r)
+  @test LinearAlgebra.norm(d(1, 0) - center(d)) == r
```
Comment (juliohm) [inline test/primitives.jl]:
```suggestion
  @test norm(d(1, 0) - center(d)) == r
```

File: test/primitives.jl [hunk 4]
```diff
@@ -842,6 +853,12 @@ end
   equaltest(c)
   isapproxtest(c)
 
+  # Ensure mixed-unit construction produces correct parametrization
+  p = Plane(cart(0, 0, 0), vector(0, 0, 1))
+  r = T(1) * u"mm"
+  c = Circle(p, r)
+  @test LinearAlgebra.norm(c(0) - center(c)) == r
```
Comment (juliohm) [inline test/primitives.jl]:
```suggestion
  @test norm(c(0) - center(c)) == r
```

File: src/Meshes.jl [hunk 5]
```diff
@@ -13,7 +13,7 @@ using Unitful
 using Random
 
 using Bessels: gamma
-using Unitful: AbstractQuantity, numtype
+using Unitful: AbstractQuantity, numtype, unit
```
Comment (juliohm) [inline src/Meshes.jl]:
```suggestion
using Unitful: AbstractQuantity, numtype
```

File: test/primitives.jl [hunk 6]
```diff
@@ -698,6 +698,11 @@ end
   @test cart(0, 0, 2) ∈ s
   @test cart(3, 5, 2) ∉ s
 
+  # Ensure mixed-unit construction produces correct parametrization
+  r = T(1) * u"mm"
+  s = Sphere(cart(0, 0, 0), r)
+  @test norm(s(1, 0) - center(s)) == r
+
```
Comment (juliohm) [inline test/primitives.jl]: This test is unrelated  to the changes.

```suggestion
```

File: test/primitives.jl [hunk 7]
```diff
@@ -798,6 +803,12 @@ end
   @test cart(0, 0, 1) ∉ d
   @test boundary(d) == Circle(p, T(2))
 
+  # Ensure mixed-unit construction produces correct parametrization
```
Comment (juliohm) [inline test/primitives.jl]:
```suggestion
  # ensure mixed-unit construction produces correct parametrization
```

File: test/primitives.jl [hunk 8]
```diff
@@ -842,6 +853,12 @@ end
   equaltest(c)
   isapproxtest(c)
 
+  # Ensure mixed-unit construction produces correct parametrization
```
Comment (juliohm) [inline test/primitives.jl]:
```suggestion
  # ensure mixed-unit construction produces correct parametrization
```

File: src/geometries/primitives/disk.jl (hunk 1 above)
Comment (juliohm) [inline src/geometries/primitives/disk.jl]:
```suggestion
  ℒ = lentype(d)
  T = numtype(ℒ)
  l = T(ρ) * radius(d)
  sφ, cφ = sincospi(2 * T(φ))
  u = ustrip(unit(ℒ), l * cφ)
  v = ustrip(unit(ℒ), l * sφ)
```

**Review by juliohm — APPROVED** [review]

**Comment by juliohm** [comment]
Patch released: https://github.com/JuliaRegistries/General/pull/139933
