### PR TITLE
Fix vertex accessor for PolyArea with inner chains

### LINKED ISSUE #73: Bug in vertex concatenation for PolyArea
I stumbled upon a bug that occurs when a `PolyArea` has no inner chains (julia 1.6.0-rc2):

```julia
julia> vertices(poly)
ERROR: ArgumentError: reducing over an empty collection is not allowed
Stacktrace:
  [1] _empty_reduce_error()
    @ Base ./reduce.jl:299
  [2] mapreduce_empty(f::Function, op::Base.BottomRF{typeof(vcat)}, T::Type)
    @ Base ./reduce.jl:342
  [3] reduce_empty(op::Base.MappingRF{Meshes.var"#175#176", Base.BottomRF{typeof(vcat)}}, #unused#::Type{Tuple{Chain{2, Float32}, Any}})
    @ Base ./reduce.jl:329
  [4] reduce_empty_iter
    @ ./reduce.jl:355 [inlined]
  [5] reduce_empty_iter
    @ ./reduce.jl:354 [inlined]
  [6] foldl_impl
    @ ./reduce.jl:49 [inlined]
  [7] mapfoldl_impl
    @ ./reduce.jl:44 [inlined]
  [8] #mapfoldl#214
    @ ./reduce.jl:160 [inlined]
  [9] mapfoldl
    @ ./reduce.jl:160 [inlined]
 [10] #mapreduce#218
    @ ./reduce.jl:287 [inlined]
 [11] mapreduce
    @ ./reduce.jl:287 [inlined]
 [12] #reduce#220
    @ ./reduce.jl:456 [inlined]
 [13] reduce
    @ ./reduce.jl:456 [inlined]
 [14] vertices(p::PolyArea{2, Float32, Chain{2, Float32}})
    @ Meshes ~/.julia/dev/Meshes/src/polytopes/polyarea.jl:51
 [15] top-level scope
    @ REPL[12]:1
```
We should either add an empty vector as `init` argument to `reduce`, or use a different concatenation method for inner chains.

### PR DESCRIPTION
**Pull request by serenity4**
Fixes #73.

### CODE REVIEW

File: src/polytopes/polyarea.jl [hunk 1]
```diff
@@ -48,7 +48,7 @@ PolyArea(outer::Vararg{TP}) where {TP<:Tuple} = PolyArea(collect(Point.(outer)))
 ==(p1::PolyArea, p2::PolyArea) =
   p1.outer == p2.outer && p1.inners == p2.inners
 
-vertices(p::PolyArea) = [vertices(p.outer); reduce(vcat, vertices(inner) for inner in p.inners)]
+vertices(p::PolyArea) = [vertices(p.outer); reduce(vcat, vertices(inner) for inner in p.inners; init=Point{embeddim(p),coordtype(p)}[])]
```
Comment (juliohm) [inline src/polytopes/polyarea.jl]:
```suggestion
function vertices(p::PolyArea{Dim,T}) where {Dim,T}
  vo = vertices(p.outer)
  vi = reduce(vcat, vertices(inner) for inner in p.inners; init=Point{Dim,T}[])
  [vo; vi]
end
```
A small refactoring to make the line shorter.

File: test/polytopes.jl [hunk 2]
```diff
@@ -186,9 +186,9 @@
 
     # test accessor methods
     poly = PolyArea(P2[(1,2),(2,3),(1,2)])
-    @test vertices(poly) == CircularVector(P2[(1,2),(2,3)])
+    @test vertices(poly) == Meshes.CircularVector(P2[(1,2),(2,3)])
```
Comment (juliohm) [inline test/polytopes.jl]: You can also add `CircularArrays` to the test/Project.toml and `using CicurlarArrays.jl` in runtests.jl

File: test/runtests.jl [hunk 3]
```diff
@@ -3,7 +3,7 @@ using Tables
 using Distances
 using Statistics
 using LinearAlgebra
-using CategoricalArrays
+using CategoricalArrays, CircularArrays
```
Comment (juliohm) [inline test/runtests.jl]:
```suggestion
using CategoricalArrays
using CircularArrays
```
