### PR TITLE
#96 Fix error in hexahedron creation for CartesianGrid

### LINKED ISSUE #96: Typo in getindex for Cartesian Grid
p3 and p7 are duplicates, formula might be wrong. It then leads to wrong centroid.
```julia
julia> using Meshes

julia> grid= CartesianGrid((20,20,20),(0,0,0),(5,5,5))
20×20×20 CartesianGrid{3,Int64}
  minimum: Point(0, 0, 0)
  maximum: Point(100, 100, 100)
  spacing: (5, 5, 5)

julia> grid[1]
Hexahedron{3,Float64}
  └─Point(0.0, 0.0, 0.0)
  └─Point(5.0, 0.0, 0.0)
  └─Point(5.0, 5.0, 0.0)
  └─Point(0.0, 5.0, 0.0)
  └─Point(0.0, 0.0, 5.0)
  └─Point(5.0, 0.0, 5.0)
  └─Point(5.0, 5.0, 0.0)
  └─Point(0.0, 5.0, 5.0)

julia> centroid(grid[1])
Point(2.5, 2.5, 1.875)
```
node_juli

### PR DESCRIPTION
**Pull request by hameye**
Fix #96

### CODE REVIEW

**Comment by juliohm** [comment]
Nice. Could you please add a simple test that constructs a 3D grid and then checks the first element with `grid[1]` to make sure the constructed hexahedron makes sense?

Another useful test to add is one that checks `centroid(grid, i) == centroid(grid[i])` for all `i in 1:nelements(grid)`.

The method `centroid(grid, i)` is more efficient than constructing a hexahedron and then computing the centroid.

**Review by juliohm — CHANGES_REQUESTED** [review]
Missing tests.

File: test/mesh.jl [hunk 1]
```diff
@@ -47,6 +47,29 @@
...
+    @test grid[1].vertices[4] == P3(0, 5, 0)
+    @test grid[1].vertices[5] == P3(0, 0, 5)
+    @test grid[1].vertices[6] == P3(5, 0, 5)
+    @test grid[1].vertices[7] == P3(5, 5, 5)
+    @test grid[1].vertices[8] == P3(0, 5, 5)
+    @test all([centroid(grid, i) == centroid(grid[i]) for i in 1:nelements(grid)])
+
+
+
+
```
Comment (juliohm) [inline test/mesh.jl]: Please do `vertices(grid[1]) == P3[(), (), (), ..., ()]`

File: test/mesh.jl [hunk 2]
```diff
@@ -47,6 +47,29 @@
...
+    @test eltype(grid) <: Hexahedron{3,T}
+    @test grid[1].vertices[1] == P3(0, 0, 0)
+    @test grid[1].vertices[2] == P3(5, 0, 0)
+    @test grid[1].vertices[3] == P3(5, 5, 0)
+    @test grid[1].vertices[4] == P3(0, 5, 0)
+    @test grid[1].vertices[5] == P3(0, 0, 5)
+    @test grid[1].vertices[6] == P3(5, 0, 5)
+    @test grid[1].vertices[7] == P3(5, 5, 5)
+    @test grid[1].vertices[8] == P3(0, 5, 5)
+    @test all([centroid(grid, i) == centroid(grid[i]) for i in 1:nelements(grid)])
```
Comment (juliohm) [inline test/mesh.jl]: I think we can do this check without materializing the array, just remove the brackets `[]` inside the `all` call.

**Review by juliohm — CHANGES_REQUESTED** [review]

File: test/mesh.jl [hunk 3]
```diff
@@ -47,6 +47,26 @@
...
+    @test nelements(grid) == 20*10*5
+    @test eltype(grid) <: Hexahedron{3,T}
+    @test vertices(grid[1]) == P3[(0, 0, 0),
+                                  (5, 0, 0),
+                                  (5, 5, 0),
+                                  (0, 5, 0),
+                                  (0, 0, 5),
+                                  (5, 0, 5),
+                                  (5, 5, 5),
+                                  (0, 5, 5)]
```
Comment (juliohm) [inline test/mesh.jl]:
```suggestion
    @test vertices(grid[1]) == P3[(0, 0, 0), (5, 0, 0), (5, 5, 0), (0, 5, 0), (0, 0, 5), (5, 0, 5), (5, 5, 5), (0, 5, 5)]
```

**Review by juliohm — APPROVED** [review]

**Comment by juliohm** [comment]
That is awesome. Thanks for the updates. I will just wait the tests to finish running and then we can merge and release a patch release with the fix.
